cssの設定を追加
Y-T0201/lamp_practice pull request #16
Opened 2020-10-26 16:34 UTC by Y-T0201

@primestyleus 
ご指摘いただいた、cssでの余白の設定と使用していない変数を削除いたしました。
ご査収の程よろしくお願いいたします。

2020-10-26 22:08 UTC, primestyleus requested changes
@Y-T0201 
CSSのパス指定がおかしいようなので、ご確認をお願いします。

2020-10-26 22:08 UTC, primestyleus commented on www/view/orders_details_view.php
> +  <link rel="stylesheet" href="<?php print( '../' . STYLESHEET_PATH . 'orders.css'); ?>">
ここの ../ は不要だと思うのですが、いかがでしょうか？

2020-10-27 00:28 UTC, Y-T0201 commented on www/view/orders_details_view.php
> +  <link rel="stylesheet" href="<?php print( '../' . STYLESHEET_PATH . 'orders.css'); ?>">
@primestyleus 
../がないとcssが反映されませんでした。

2020-10-27 01:33 UTC, primestyleus requested changes

2020-10-27 01:33 UTC, primestyleus commented on www/view/orders_details_view.php
> +  <link rel="stylesheet" href="<?php print( '../' . STYLESHEET_PATH . 'orders.css'); ?>">
@Y-T0201 
../なしで正常に動作することをこちらで検証しています。
再度ご確認ください。

2020-10-27 02:03 UTC, Y-T0201 commented
@primestyleus 
css反映されました。
お騒がせして申し訳ございませんでした。

2020-10-27 02:54 UTC, primestyleus approved these changes

2020-10-27 02:54 UTC, merged

2020-10-27 02:55 UTC, primestyleus commented
@Y-T0201 マージしました。