ページネーション修正
Y-T0201/lamp_practice pull request #21
Opened 2020-10-29 15:10 UTC by Y-T0201

@primestyleus 
ページネーション機能実装の際にご指摘いただいた箇所を修正いたしました。
コードレビューいただけますと幸いです。

2020-10-29 22:50 UTC, primestyleus requested changes
@Y-T0201 

改善している点もありますが、できていない点もあります。

> 商品取得関数のオプション引数（デフォルト値の設定された引数）としてLIMIT句の設定値を渡すことができると非常に便利です。挑戦してみましょう。

もしこちらを対応しているのだとすると、今回の内容では対応できていません。

2020-10-29 22:50 UTC, primestyleus commented on www/html/index.php
> +if (isset($_GET['page']) === false) {
emptyなどを使って判定したほうがいいかと思います。せっかくget_getの中でissetの判定をしているのに、呼び出し側でまた同じ処理をするのでは意味がありません。

2020-10-29 22:50 UTC, primestyleus commented on www/view/index_view.php
> +    <nav class="...">
class="..."は、なぜ必要なのでしょうか？

2020-10-30 01:00 UTC, Y-T0201 commented
@primestyleus 
丁寧なご指摘ありがとうございます。
修正いたしました。
コードレビューの程、よろしくお願いいたします。

2020-10-30 04:04 UTC, primestyleus requested changes

2020-10-30 04:04 UTC, primestyleus commented on www/model/item.php
> +function get_8_items($db, $is_open = false, $start=0, $one_page_items){
$one_page_itemsを追加したいただいたのはわかりますが、オプション引数にはなっていません。ほかも同様です。

2020-10-30 08:59 UTC, Y-T0201 commented on www/model/item.php
> +function get_8_items($db, $is_open = false, $start=0, $one_page_items){
@primestyleus 
オプション引数がよく分かっていないので、次回のレッスンのときに教えてください。

2020-11-03 03:39 UTC, Y-T0201 commented
@primestyleus 
オプション引数を追加いたしました。
コードレビューの程、よろしくお願いいたします。

2020-11-03 04:02 UTC, primestyleus approved these changes
@Y-T0201 
get_8_itemsは使ってないのであれば消したほうが、一旦okとします。

2020-11-03 04:02 UTC, merged

2020-11-03 11:00 UTC, Y-T0201 commented
@primestyleus 
ご指摘ありがとうございます。