トークンの生成、照合、破棄の追加
Y-T0201/lamp_practice pull request #8
Opened 2020-10-18 06:28 UTC by Y-T0201

@primestyleus 
トークンの生成、照合、破棄の追加をいたしました。
コードレビューの程、よろしくお願いいたします。

2020-10-18 10:40 UTC, primestyleus requested changes
@Y-T0201 
動作確認してみてください。
-トークンがフォームにセットされない
- トークン認証失敗しても、処理は実行される
といった問題があります。

2020-10-18 13:38 UTC, Y-T0201 commented
@primestyleus 

コードレビューをしていただき、ありがとうございます
2点修正します。

1.トークン生成時に以下を記入。
`$token = get_csrf_token();`

2.トークンの照合時に以下を記入。
```
if(is_valid_csrf_token($token) === true) {
  unset($_SESSION['csrf_token']);
}else {
  set_error('商品の登録に失敗しました。');
}
```

2020-10-18 16:29 UTC, primestyleus commented
@Y-T0201 
修正の方針はよいので、実際にコードを修正されたらまたご連絡ください。
またマージコンフリクト（競合）が発生しています。こちらもまずは自己解決できるか挑戦してみてください。

2020-10-19 03:11 UTC, Y-T0201 commented
@primestyleus
トークンの生成と照合を修正いたしました。
お手数をお掛けいたしますが、再度コードレビューの程、よろしくお願いいたします。

2020-10-19 04:15 UTC, primestyleus requested changes
@Y-T0201 
まだトークンが一致しなくても処理は行われる作りのママのようです。動作確認してください。(検証ツールでフォームにセットされたトークンをいじることで、トークンが一致しない場合の検証ができます)

2020-10-19 08:41 UTC, Y-T0201 commented
@primestyleus 
長文失礼します。
以下のようにコード修正したところ、トークンが一致しているかの確認ができました。
ただ、教科書に記載されていたユーザー関数を使用していないのですが、実装してよろしいでしょうか。
（私が教科書のユーザー関数を理解できておらず、使うことができないです。）
```
// トークンの照合
if (isset($_POST['token']) === true) {
  if($_POST['token'] === $_SESSION['csrf_token']) {
    unset($_SESSION['csrf_token']);
    // カートの数量を変更
    if(update_cart_amount($db, $cart_id, $amount)){
      set_message('購入数を更新しました。' );
    } else {
      set_error('購入数の更新に失敗しました。');
    }
  } else {
    set_error('トークンの照合に失敗しました。');
  }
} else {
  set_error('POSTエラー発生');
}
```

2020-10-19 13:26 UTC, primestyleus commented
@Y-T0201 

間違いではないですが、ここまでのユーザ関数を使う設計のほうがきれいです。
以下のようにコード修正できないでしょうか？

```
if(is_valid_csrf_token($token) === true) {
    // 正常に処理を実行
}else {
    // エラー処理（登録・更新・削除等の処理は行わない）
}
```

2020-10-20 13:04 UTC, Y-T0201 commented
@primestyleus 
トークンの照合の箇所を修正いたしました。
コードレビューの程、よろしくお願いいたします。

2020-10-20 16:18 UTC, primestyleus approved these changes
@Y-T0201 
余計な記述が1行ありますが、一旦OKとします。どこかのタイミングで消していただければと思います。

2020-10-20 16:18 UTC, primestyleus commented on www/html/cart.php
> +$_SESSION['csrf_token'] = $token;
こちらの1行は不要です。get_csrf_token()関数の中で、セッションに保存をしているからです。

2020-10-20 16:18 UTC, merged

2020-10-20 16:26 UTC, Y-T0201 commented on www/html/cart.php
> +$_SESSION['csrf_token'] = $token;
@primestyleus 
ご指摘ありがとうございます。
次回の課題のときに、修正します。